# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg7bTAn4cATaklrtrVaBUmR10GyLMwEk
"""

#1-topshiriq
import matplotlib.pyplot as plt
import numpy as np
x=np.linspace(0,10,100)
print(x)
y=4+2* np.sin(2*x)
print(y)
fig,ax= plt.subplots()
ax.plot(x,y, linewidth=2.0)
plt.show()



import matplotlib.pyplot as plt
import numpy as np
np.random.seed(3)
x=4+np.random.normal(0,2,24)
y=4+np.random.normal(0,2,len(x))
sizes=np.random.uniform(15,80,len(x))
colors=np.random.uniform(15,80,len(x))
fig,ax=plt.subplots()
ax.scatter(x,y,s=sizes,c=colors,vmin=0,
vmax=100)
ax.set(xlim=(0,8),xticks=np.arange(2,7),
       ylim=(0,8),yticks=np.arange(2,7))
plt.show()