# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzdiE0L9c_e9i6voqANwMvjgSWSDjOI6
"""

pip install opencv-python



from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mmmmm.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("mexriniso.png")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("foziljonova.png")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)